# Generated by Django 2.0.2 on 2018-02-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='unusListElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_element', models.CharField(max_length=255)),
                ('done', models.BooleanField()),
            ],
        ),
    ]
